### PR TITLE
temp fix on #665

### PR DESCRIPTION
**Pull request by aaassseee**

### CODE REVIEW

**Comment by Larpoux** [comment]
Thank you so much @aaassseee  for your Pull Request.
Not many developers do Pull Request. I really appreciate your.
I will look to it this week.
Thank you again for your contribution.

**Comment by aaassseee** [comment]
It is a crash workaround only.
It didn't fix anything

**Comment by Larpoux** [comment]
That’s OK. I will look to your PR and see if I can improve it with a real fix.
Anyway, a workaround to avoid a crash is always a good thing.
Take care.

**Comment by Larpoux** [comment]
@aaassseee ,

Your Pull Request has been integrated into Flutter Sound 8.1.3
Thank you again for your contribution

**Pull request merged**
