### PR TITLE
Attempt to fix flutterSound registering to flutter engine that's runn…

### PR DESCRIPTION
**Pull request by ed-fx**
This is my attempt to fix 
https://github.com/Canardoux/tau/issues/594

This works for my use case, however, I'm not sure if this works for all other use cases.

### CODE REVIEW

**Comment by Larpoux** [comment]
Thank you so much, @ed-fx

**Comment by Larpoux** [comment]
In my TODO list, Pull Requests are on the top of everything else (but unfortunately nobody does Pull Request, ususally).

You are now on top : I will consider your PR tomorrow 😉 .

**Comment by Larpoux** [comment]
May I ask you to kindly do your Pull Request on the "BeforeNullSafety" branch ?

**Comment by ed-fx** [comment]
@Larpoux Done.

**Pull request merged**
